# -*- coding: utf-8 -*-
"""INTERFACE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_M2zxW8n6TZKZCqPrGN3YwWEbDjvqQ9
"""
import pandas as pd
import numpy as np
from scipy import stats
import streamlit as st
import folium
from streamlit_folium import st_folium # Necesario para pintar el mapa en la web
from folium import plugins

# 1. TÍTULO Y CONFIGURACIÓN
st.set_page_config(page_title="Incendios Coruña", layout="wide")
st.title("🔥 Análisis de Incendios en A Coruña")
st.write("Esta aplicación muestra la evolución temporal y la ubicación de los incendios.")

import zipfile

# BLOQUE PARA LEER ZIP DE MAC CORRECTAMENTE
with zipfile.ZipFile('fires-all.csv.zip') as z:
    # Buscamos el archivo .csv real ignorando la basura de Mac (__MACOSX)
    nombre_archivo = [f for f in z.namelist() if f.endswith('.csv') and '__MACOSX' not in f][0]
    
    # Abrimos ese archivo específico
    with z.open(nombre_archivo) as f:
        df_incendios = pd.read_csv(f, parse_dates=['fecha'], index_col='fecha')
        
# Filtramos por provincia (A Coruña es 15)
df_coruna = df_incendios[df_incendios['idprovincia'] == 15]

# --- SECCIÓN 2: EL MAPA (FOLIUM) ---
st.subheader("2. Mapa de Calor Animado")
st.write("Mapa que muestra la evolución mes a mes.")
filtro = (df_coruna.index.year == 2006)
df_agosto_2006 = df_coruna[filtro]

# 1. PREPARACIÓN: Quitamos las filas que no tengan coordenadas
# Creamos una copia para no modificar el original
df_mapa = df_agosto_2006.dropna(subset=['lat', 'lng']).copy()

# 2. CENTRAR EL MAPA
# Calculamos el centro promedio de tus datos para que el mapa empiece ahí
centro_mapa = [df_mapa['lat'].mean(), df_mapa['lng'].mean()]

m = folium.Map(location=centro_mapa, zoom_start=9)

# 3. PINTAR LOS PUNTOS
for index, row in df_mapa.iterrows():
    # Creamos un texto para el popup con el municipio y la superficie
    info_popup = f"Municipio: {row['municipio']} - Superficie: {row['superficie']} ha"

    folium.CircleMarker(
        location=[row['lat'], row['lng']], # Cuidado: aquí es 'lng', no 'lon'
        radius=3,                          # Tamaño del punto
        popup=info_popup,                  # La info que sale al clicar
        color="red",                       # Color del borde (rojo por ser fuego)
        fill=True,
        fill_color="orange",               # Color de relleno
        fill_opacity=0.7
    ).add_to(m)

    # ¡ESTO ES LO IMPORTANTE! Usamos st_folium para mostrarlo
    st.write(f"Mostrando mapa con **{len(df_mapa)}** incendios geolocalizados.")
    st_folium(m, width=1000, height=500)
else:
    st.write("No hay datos de incendios con coordenadas válidas para mostrar en el mapa.")
